### ISSUE TITLE
Error during sitemap.xml generation

### ISSUE THREAD

**Issue by gabriel-cardoso** [para-cms/para-seo_tools#5]
`Errno::ENOENT: No such file or directory @ rb_file_s_stat - /tmp/sitemap.xml20150611-9512-qb1kld` 
when running 
`rake seo_tools:sitemap:generate`

Full trace: 

``` bash
rake aborted!
Errno::ENOENT: No such file or directory @ rb_file_s_stat - /tmp/sitemap.xml20150611-9551-gkf2ps
/home/gcardoso/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1573:in `stat'
/home/gcardoso/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1573:in `block in fu_each_src_dest'
/home/gcardoso/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1589:in `fu_each_src_dest0'
/home/gcardoso/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
/home/gcardoso/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:514:in `mv'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/sitemap-0.3.3/lib/sitemap/generator.rb:175:in `block in save'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/sitemap-0.3.3/lib/sitemap/generator.rb:173:in `each'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/sitemap-0.3.3/lib/sitemap/generator.rb:173:in `each_with_index'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/sitemap-0.3.3/lib/sitemap/generator.rb:173:in `save'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/bundler/gems/seo_tools-para-a63023bad3df/lib/tasks/sitemap.rake:9:in `block (3 levels) in <top (required)>'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/gcardoso/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/bin/rake:23:in `load'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/bin/rake:23:in `<main>'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/bin/ruby_executable_hooks:15:in `eval'
/home/gcardoso/.rvm/gems/ruby-2.1.3@eau-bien-etre-wpi/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => seo_tools:sitemap:generate
```

**Comment by vala** [comment]
Tried to find info on that issue in https://github.com/viseztrance/rails-sitemap ? The backtrace indicates that the error happens at that level

**Comment by gabriel-cardoso** [comment]
Task code works from console though. Investigating
